export type MetricDirection = "higher_better" | "lower_better" | "context";

export type MetricDefinition = {
  key: string;
  displayName: string;
  clinicianName: string;
  plainMeaning: string;
  clinicalWhyItMatters: string;
  interpretation: string;
  limitation: string;
  direction: MetricDirection;
  showInClinicianView: boolean;
  showInResearchView: boolean;
  showCI: boolean;
  format: "number" | "percent" | "count" | "text";
  methodVaultDefinition: string;
};

export const metricDefinitions: Record<string, MetricDefinition> = {
  deployment_status: {
    key: "deployment_status",
    displayName: "Recommendation",
    clinicianName: "Validation use guidance",
    plainMeaning: "A summary of how much review the current validation evidence suggests.",
    clinicalWhyItMatters: "It turns the validation output into a practical review posture for doctors and hospital AI teams.",
    interpretation: "Use it as a review-intensity guide, not as a binary approval label.",
    limitation: "It depends on the uploaded validation set size and configured failure-pattern thresholds.",
    direction: "context",
    showInClinicianView: true,
    showInResearchView: false,
    showCI: true,
    format: "text",
    methodVaultDefinition: "Derived from review-priority severity, case count, and recommendation confidence.",
  },
  lesion_recall: {
    key: "lesion_recall",
    displayName: "Lesion recall",
    clinicianName: "Lesion detection rate",
    plainMeaning: "Of the expert-marked lesions, how many did the AI find?",
    clinicalWhyItMatters: "Low lesion detection means the AI may miss lesions the reader still needs to notice.",
    interpretation: "Higher is better.",
    limitation: "It does not tell whether lesion boundaries are perfect.",
    direction: "higher_better",
    showInClinicianView: true,
    showInResearchView: true,
    showCI: true,
    format: "number",
    methodVaultDefinition: "Matched GT lesions divided by total GT lesions.",
  },
  lesion_precision: {
    key: "lesion_precision",
    displayName: "Lesion precision",
    clinicianName: "Confirmed AI lesion candidates",
    plainMeaning: "Of the AI-predicted lesions, how many matched the expert mask?",
    clinicalWhyItMatters: "Low precision means the model may create extra lesion candidates that inflate count or burden.",
    interpretation: "Higher is better.",
    limitation: "Some prediction-only regions may reflect annotation uncertainty and should be reviewed visually.",
    direction: "higher_better",
    showInClinicianView: true,
    showInResearchView: true,
    showCI: true,
    format: "number",
    methodVaultDefinition: "Matched predicted lesions divided by total predicted lesions.",
  },
  fp_lesions_per_scan: {
    key: "fp_lesions_per_scan",
    displayName: "FP lesions / scan",
    clinicianName: "Extra AI lesion candidates",
    plainMeaning: "How many extra predicted lesions appeared that did not match the expert mask?",
    clinicalWhyItMatters: "High values can inflate lesion count or create misleading lesion burden.",
    interpretation: "Lower is better.",
    limitation: "Prediction-only regions may still deserve visual review before being dismissed.",
    direction: "lower_better",
    showInClinicianView: true,
    showInResearchView: true,
    showCI: false,
    format: "number",
    methodVaultDefinition: "Predicted components without a matched GT lesion, averaged per scan.",
  },
  fn_lesions_per_scan: {
    key: "fn_lesions_per_scan",
    displayName: "FN lesions / scan",
    clinicianName: "Missed expert lesions",
    plainMeaning: "How many expert lesions were not captured by the AI per scan?",
    clinicalWhyItMatters: "This directly identifies how much lesion review remains necessary.",
    interpretation: "Lower is better.",
    limitation: "Small samples can make this value unstable.",
    direction: "lower_better",
    showInClinicianView: true,
    showInResearchView: true,
    showCI: false,
    format: "number",
    methodVaultDefinition: "Unmatched GT components averaged per scan.",
  },
  relative_volume_error: {
    key: "relative_volume_error",
    displayName: "Relative volume error",
    clinicianName: "Lesion-burden volume error",
    plainMeaning: "How far the AI’s total lesion volume is from the expert volume.",
    clinicalWhyItMatters: "Important if the model output is used for lesion-burden monitoring.",
    interpretation: "Lower is better.",
    limitation: "Volume agreement can look acceptable even when individual lesions are missed.",
    direction: "lower_better",
    showInClinicianView: true,
    showInResearchView: true,
    showCI: false,
    format: "number",
    methodVaultDefinition: "Absolute volume difference divided by expert lesion volume.",
  },
  high_risk_location_miss_rate: {
    key: "high_risk_location_miss_rate",
    displayName: "High-risk location miss rate",
    clinicianName: "Small important-location misses",
    plainMeaning: "How often tiny/small lesions in important MS-related brain locations were missed.",
    clinicalWhyItMatters: "Small missed lesions may matter when reviewing subtle disease burden.",
    interpretation: "Lower is better.",
    limitation: "Depends on anatomy label quality and lesion annotation quality.",
    direction: "lower_better",
    showInClinicianView: true,
    showInResearchView: true,
    showCI: true,
    format: "number",
    methodVaultDefinition: "Missed tiny/small GT lesions in PV, JC/cortical, or infratentorial locations divided by all such lesions.",
  },
  clinical_topography_preservation_ratio: {
    key: "clinical_topography_preservation_ratio",
    displayName: "Topography preservation",
    clinicianName: "Brain-location evidence preservation",
    plainMeaning: "Whether the AI preserves the same MS-relevant brain-location pattern seen in the expert mask.",
    clinicalWhyItMatters: "Location evidence matters because lesions in different brain regions can carry different review importance.",
    interpretation: "Higher is better.",
    limitation: "This is a brain MRI topography proxy; it is not a diagnostic criterion.",
    direction: "higher_better",
    showInClinicianView: true,
    showInResearchView: true,
    showCI: false,
    format: "number",
    methodVaultDefinition: "Preserved relevant GT locations divided by GT relevant locations.",
  },
  dice_voxel: {
    key: "dice_voxel",
    displayName: "Dice",
    clinicianName: "Overall mask overlap",
    plainMeaning: "How much the AI mask overlaps with the expert mask overall.",
    clinicalWhyItMatters: "Useful for broad mask agreement, but it can hide missed small lesions.",
    interpretation: "Higher is better.",
    limitation: "A model can have acceptable Dice while missing important lesion types.",
    direction: "higher_better",
    showInClinicianView: false,
    showInResearchView: true,
    showCI: false,
    format: "number",
    methodVaultDefinition: "Two times overlap divided by the sum of expert and AI mask voxels.",
  },
  hd95_mm: {
    key: "hd95_mm",
    displayName: "HD95",
    clinicianName: "Boundary outlier distance",
    plainMeaning: "A boundary error measure showing how far lesion borders can be from the expert border.",
    clinicalWhyItMatters: "Useful when boundary accuracy matters for volume tracking.",
    interpretation: "Lower is better.",
    limitation: "Harder to interpret clinically than lesion detection.",
    direction: "lower_better",
    showInClinicianView: false,
    showInResearchView: true,
    showCI: false,
    format: "number",
    methodVaultDefinition: "95th percentile symmetric surface distance in millimeters.",
  },
  assd_mm: {
    key: "assd_mm",
    displayName: "ASSD",
    clinicianName: "Average boundary distance",
    plainMeaning: "The average surface distance between AI and expert lesion borders.",
    clinicalWhyItMatters: "Helps quantify boundary quality for volume-sensitive workflows.",
    interpretation: "Lower is better.",
    limitation: "Does not directly say how many lesions were missed.",
    direction: "lower_better",
    showInClinicianView: false,
    showInResearchView: true,
    showCI: false,
    format: "number",
    methodVaultDefinition: "Average symmetric surface distance in millimeters.",
  },
  confidence_interval: {
    key: "confidence_interval",
    displayName: "Confidence interval",
    clinicianName: "Uncertainty range",
    plainMeaning: "A range showing uncertainty around the metric estimate.",
    clinicalWhyItMatters: "Wide intervals mean the estimate is less certain, often because few cases or lesions were tested.",
    interpretation: "Narrower is more stable.",
    limitation: "Intervals describe this validation cohort, not all future patients.",
    direction: "context",
    showInClinicianView: true,
    showInResearchView: true,
    showCI: false,
    format: "text",
    methodVaultDefinition: "Displayed where a denominator is available for local count-based estimates.",
  },
};

export function getMetricDefinition(key: string) {
  return metricDefinitions[key] || null;
}
